//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 02:57:50 PM CET 
//


package org.alfresco.repo.cmis.rest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieldFacet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fieldFacet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countDocsMissingFacetField" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enumMethodCacheMinDF" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="method" type="{http://lucene.apache.org/solr}fieldFacetMethod" minOccurs="0"/>
 *         &lt;element name="minCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sort" type="{http://lucene.apache.org/solr}fieldFacetSort" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fieldFacet", propOrder = {
    "countDocsMissingFacetField",
    "enumMethodCacheMinDF",
    "field",
    "limit",
    "method",
    "minCount",
    "offset",
    "prefix",
    "sort"
})
public class FieldFacet {

    protected boolean countDocsMissingFacetField;
    protected int enumMethodCacheMinDF;
    protected String field;
    protected int limit;
    protected FieldFacetMethod method;
    protected int minCount;
    protected int offset;
    protected String prefix;
    protected FieldFacetSort sort;

    /**
     * Gets the value of the countDocsMissingFacetField property.
     * 
     */
    public boolean isCountDocsMissingFacetField() {
        return countDocsMissingFacetField;
    }

    /**
     * Sets the value of the countDocsMissingFacetField property.
     * 
     */
    public void setCountDocsMissingFacetField(boolean value) {
        this.countDocsMissingFacetField = value;
    }

    /**
     * Gets the value of the enumMethodCacheMinDF property.
     * 
     */
    public int getEnumMethodCacheMinDF() {
        return enumMethodCacheMinDF;
    }

    /**
     * Sets the value of the enumMethodCacheMinDF property.
     * 
     */
    public void setEnumMethodCacheMinDF(int value) {
        this.enumMethodCacheMinDF = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public int getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(int value) {
        this.limit = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link FieldFacetMethod }
     *     
     */
    public FieldFacetMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldFacetMethod }
     *     
     */
    public void setMethod(FieldFacetMethod value) {
        this.method = value;
    }

    /**
     * Gets the value of the minCount property.
     * 
     */
    public int getMinCount() {
        return minCount;
    }

    /**
     * Sets the value of the minCount property.
     * 
     */
    public void setMinCount(int value) {
        this.minCount = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link FieldFacetSort }
     *     
     */
    public FieldFacetSort getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldFacetSort }
     *     
     */
    public void setSort(FieldFacetSort value) {
        this.sort = value;
    }

}
