//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 02:57:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://lucene.apache.org/solr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.alfresco.repo.cmis.rest;
